namespace Server.Models;

public class Item
{
    public int Id { get; set; }
    
    // The unique ID generated by the user's template (e.g., "LAPTOP-001")
    public string CustomId { get; set; } = string.Empty;
    
    // Automatically records when the item was made. DateTime.UtcNow is the safest standard.
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Foreign Key: Links this item to its parent inventory.
    public int InventoryId { get; set; }
    public Inventory Inventory { get; set; } = null!;

    // --- THE FIXED DATA COLUMNS ---
    // These match up with the definitions in the Inventory table.
    // They are nullable ("?") because an item might not use all 3 string fields.
    public string? String1Value { get; set; } 
    public string? String2Value { get; set; }
    public string? String3Value { get; set; }

    // For numbers, we use double or int. "double?" means it can be a number or null.
    public double? Number1Value { get; set; }
    // (You will add the remaining Number, Text, Bool, and Link value properties here)

    // Optimistic Concurrency Token: This fulfills the requirement that prevents two people 
    // from overwriting an item at the exact same time. EF Core handles this automatically.
    public uint Version { get; set; }
}