// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Models;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bool1Name")
                        .HasColumnType("text");

                    b.Property<bool>("Bool1Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Bool2Name")
                        .HasColumnType("text");

                    b.Property<bool>("Bool2Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Bool3Name")
                        .HasColumnType("text");

                    b.Property<bool>("Bool3Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomIdTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Number1Name")
                        .HasColumnType("text");

                    b.Property<bool>("Number1Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Number2Name")
                        .HasColumnType("text");

                    b.Property<bool>("Number2Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Number3Name")
                        .HasColumnType("text");

                    b.Property<bool>("Number3Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("String1Name")
                        .HasColumnType("text");

                    b.Property<bool>("String1Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("String2Name")
                        .HasColumnType("text");

                    b.Property<bool>("String2Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("String3Name")
                        .HasColumnType("text");

                    b.Property<bool>("String3Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Text1Name")
                        .HasColumnType("text");

                    b.Property<bool>("Text1Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Text2Name")
                        .HasColumnType("text");

                    b.Property<bool>("Text2Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Text3Name")
                        .HasColumnType("text");

                    b.Property<bool>("Text3Visible")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Server.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Bool1Value")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Bool2Value")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Bool3Value")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Number1Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("Number2Value")
                        .HasColumnType("double precision");

                    b.Property<double?>("Number3Value")
                        .HasColumnType("double precision");

                    b.Property<string>("String1Value")
                        .HasColumnType("text");

                    b.Property<string>("String2Value")
                        .HasColumnType("text");

                    b.Property<string>("String3Value")
                        .HasColumnType("text");

                    b.Property<string>("Text1Value")
                        .HasColumnType("text");

                    b.Property<string>("Text2Value")
                        .HasColumnType("text");

                    b.Property<string>("Text3Value")
                        .HasColumnType("text");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "CustomId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Server.Models.Inventory", b =>
                {
                    b.HasOne("Server.Models.User", "User")
                        .WithMany("Inventories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Item", b =>
                {
                    b.HasOne("Server.Models.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Server.Models.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
